### ISSUE TITLE
Tasks create checkboxes instead of ac:task 

### ISSUE THREAD

**Issue by karooga** [zacanger/md2conf#2]
According to the https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html  I think tasks as used in Confluence should be represented as ac:tasks within an ac:task-list rather than an (input) checkbox.  While the output displayed in confluence looks correct the functionality of being able to persist task state changes does not work across page refreshes.

# Is this a feature request or a bug?

It could well have been the intent to use checkboxes and I can't say it's wrong from a visual perspective.  However if one is trying to get confluence functionality out the box then this is probably a bug.

# Expected behavior:
Given input: 
// - [ ] Get snack

```html
// output:
<ac:task-list>
<ac:task>
<ac:task-status>incomplete</ac:task-status>
<ac:task-body>
      <span class="placeholder-inline-tasks">Get snack</span>
    </ac:task-body>
</ac:task>
</ac:task-list>
```

# Actual behavior:
// const md = require('md2conf')
// console.log(md('- [ ] Get snack'))

```html
// Output:
 * <input disabled="" type="checkbox"> Get snack
```

# Environment info (relevant browser, OS, etc.; run `npx envinfo`):

Independent of environment.

**Comment by zautumnz** [comment]
Thanks for the report @karooga! I'm not incredibly handy with Confluence markup, but I haven't been able to get a task list working without using the rich text editor. Do you know the syntax for a task list using their markup format?
